POST https://node-do-zero-ty.onrender.com/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "This is a test video",
    "duration": 120
}

###
GET https://node-do-zero-ty.onrender.com/videos


###
PUT https://node-do-zero-ty.onrender.com/videos/e38fd02a-19ca-464b-bddb-27dfc916f16b
Content-Type: application/json

{
    "title": "My Video - Updated",
    "description": "This is a test video",
    "duration": 120
}

###
DELETE https://node-do-zero-ty.onrender.com/videos/e38fd02a-19ca-464b-bddb-27dfc916f16b